### ISSUE TITLE
[BUG] Switching between the Packages and Developers ‘tabs’ in the search tab clears the search bar

### ISSUE THREAD

**Issue by mpelteshki** [AppTapp/Installer-Issues#104]
**Describe the bug**
Switching between the Packages and Developers views in the search tab while having anything written in the search box clears the text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Write anything in the search box
2. Switch from searching in packages to developers

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
I expect the text to remain in the search box

**Screenshots or videos**

https://user-images.githubusercontent.com/39273158/103422438-1abc3e80-4baa-11eb-814a-657f30de7b28.MP4

**Device (please complete the following information):**
 - Installer version: [5.1-70]
 - iOS: [iOS 14.2]
 - Jailbreak [Odysseyra1n]
 - Device [iPhone 7]

**Comment by SynnyGR** [comment]
Hi,

Thanks for your report.
However what you describe here is the normal behavior. Since both searches types aren't compatible, it's normal to clear the search bar in order to prevent unwanted result / lagging issues.
So what you would have to do here is that if you want to search for developer, then write your text AFTER having switched tabs.

Regards
