### ISSUE TITLE
[CRASH] On launch [No Crashlog Generated]

### ISSUE THREAD

**Issue by dragoon65** [AppTapp/Installer-Issues#105]
I open installer I click on welcome and it closes directly and after every time I open it it closes

**Comment by AppTapp** [comment]
Can you please provide us with a crash log? Please install Cr4shed in order to get a crash log and then upload it here. Without a crash log we cannot do anything since we cannot find the issue.

**Comment by dragoon65** [comment]
I would like to do it but Crashed didn't tell me I just recorded a video

**Comment by dragoon65** [comment]
here is the video https://drive.google.com/file/d/1nbP8CEzpxLEe4hZWeCWnY77fy-lxKJy8/view?usp=drivesdk

**Comment by AppTapp** [comment]
Thank you for the video, we have a few more questions: 
- what jailbreak
- iOS version 
- what device are you using? 
- Did you have Installer installed before? 
- Did Installer ever launch to show the import sources screen?

**Comment by dragoon65** [comment]
Checkra1n
14.2
iPhone X
yes when I was under iOS 13.5
and I tested it in safe mode and it works so it must come from a tweak

**Comment by SynnyGR** [comment]
Hello,

Main Installer developer here.

Thanks for your report.
First of all sorry for any inconveniences.

Since you didn't get any crashlog it will be difficult for me to do anything.
What you could do however is to first make sure Installer is truly closed, go to /var/mobile/Library/Application Support using Filza for example and remove the folder called "Installer" (please note that this will wipe your Installer setup, your sources and settings if you prefer) and tell me if that work again.

Thanks in advance for your reply.

Regards

**Comment by SynnyGR** [comment]
If this doesn't work, that'll mean the issue is effectively caused by a tweak in which case we couldn't do anything :/

**Comment by SynnyGR** [comment]
Closed due to no response from user
