### ISSUE TITLE
Suggestion: UI Improvements

### ISSUE THREAD

**Issue by yur1xpp** [AppTapp/Installer-Issues#112]
I have some suggestion regarding the UI design of Installer v5.1, hopefully the team will take these into consideration:

1. **Don't shrink text inside the button.** I feels like the shrink-ed text inside the button is very inconsistent and not very user friendly. For example:
Normal: https://ibb.co/DRLvx7M
Shrink: https://ibb.co/rkLnHWF

2. **Switch the "Changes" and "Sources" tab.** I think the "Sources" and "Changes" tab ought to switch the position. I'm not a designer myself, but I feels like most users are right-handed, and the items that are from the middle to the right of the screen should be reserved for frequently used items, in this case, the "Changes" tab. These items should be easily reached by thumb from the bottom of the screen.

3. **Swipe action on the package entry** instead of needing to enter its tweak depiction page in order to perform any action, such as remove or reinstall.

**Comment by AppTapp** [comment]
Thank you for your feedback!

Let us address each of your points. 

1. That’s a small UI bug which we honestly forgot about. This will be fixed in the upcoming release.
2. We did a lot of UX work on this, and this seems to be the tab layout people are most comfortable with. This is mostly because we use the same tab layout as Cydia here, and most people are/were very familiar with that layout. 74% voted for this layout when we polled out testers.
3. We will be (re)adding that soon. We had that functionality in Installer 5.1 but it hasn’t yet been implemented in 5.1, but we will add them soon enough :-) 

Once issues 1 & 3 are addressed, I’ll update this thread and close the issue. 

Once again, thank you for your feedback! :-)

**Comment by SynnyGR** [comment]
Hi there,

The get button width issue has been fixed.
As for the swipe options there are present with any cells that doesn't have a get button in them (in the packages list under the Sources tab for exemple). But there was effectively an issue in the installed tab in which the swipe actions have been implemented back.

These changes should be available in the next beta.

Have a nice day.

Regards
