### ISSUE TITLE
Lost repo 

### ISSUE THREAD

**Issue by Schonauban** [AppTapp/Installer-Issues#113]
I lost all my repo's with the new update...
How can I find them back because it's a lot of work, I've been using install for a very long time and I can't remember all the repo heads...
Are they still stored somewhere...?

**Comment by AppTapp** [comment]
Installer 5.1 uses a different database than Installer 5.0, which is not compatible. This meant Installer had to wipe its database in order to function correctly, which would lead to sources being reset. This was explicitly mentioned in the release post and in the package depiction. Please read the description when you install our packages because it often contains very important information. Unfortunately you will have to add your sources again, if you never added them to other package managers :(
