### ISSUE TITLE
Crash when updating tweaks (w log)

### ISSUE THREAD

**Issue by rastafaa** [AppTapp/Installer-Issues#115]
[Installer crash log.txt](https://github.com/AppTapp/Installer-Issues/files/5759663/Installer.crash.log.txt)

I had some other crashes but don’t have logs for them because I had the process blacklisted (due to constant crashes in previous Installer version)

I believe this crash occurred during a package update process.

Attached log

The install process completed successfully upon restarting app.

**Comment by rastafaa** [comment]
Love the update by the way!! Muchhh better than previous release. I was surprised to see that it doesn’t go light/dark mode according to system setting? Also some package details won’t load (especially if it’s not connected to a source)

**Comment by AppTapp** [comment]
Thank you for the report & the log. We will look into the issue asap.

> Also some package details won’t load (especially if it’s not connected to a source)

Do you have an example?

**Comment by SynnyGR** [comment]
Hi,

Thanks for your report.
Regarding the package depiction when they are installed locally (with the jailbreak for example) it's the normal behavior when an option is activated under Settings > General. Simply turn off "Web depiction as fallback" and you'll be good to go.

As for the crash mentioned it's caused by an empty url for the started package download (during install or update). This case shouldn't happen and to be honest I have no clue how this could have happened so I added a security check to avoid the crash when this rare case is encountered. If you have that issue again, please note the package, version to be upgraded to, repo url. That should be enough to point to the right direction ;)

Have a nice day !

Regards
