### ISSUE TITLE
[SUGGESTION] Ability to quickly remove package without having to wait sources refreshing task to finish

### ISSUE THREAD

**Issue by yur1xpp** [AppTapp/Installer-Issues#130]
**Is your feature request related to a problem? Please describe.**
Usually, when the sources are automatically refreshing after launching, user unable to quickly remove or "Modify" package through the "Installed" tab, as the queue at the bottom are not visible. Cydia and Zebra could allow you to do so without having to wait for it to finish. This is very useful when your intention of launching Installer is to quickly remove a package, and not anything else.

**Describe the solution you'd like**
Perhaps stack the queue bar above the "Task in Progress"?

**Comment by vanwijkdave** [comment]
Thanks for both your suggestions! We think these would be an amazing addition to Installer and we'll try to incorporate them! So be sure to stay tuned 😉

Cheers

**Comment by SynnyGR** [comment]
Hi,

Main Installer developper here.

Unfortunately, due to the nature of Installer (being a mix of native code and apt, increasing performances) we can't do this. Effectively during sources refresh, apt is used at the end of the operation in order to save some package informations, and we can't use it at the same time to modify the state of a package. That's why we disallow package operations while refreshing sources.

Have a nice day!

Regards
