### ISSUE TITLE
[BUG]Installer can't read Packages.bz2 in some repos and shows them as empty

### ISSUE THREAD

**Issue by LightningFerix** [AppTapp/Installer-Issues#158]
**Describe the bug**
When adding specific sources returns message “The server responded with invalid data.”

**To Reproduce**
Add source: https://ocean.webjungle.ch/

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Expected behavior is for the source to be added so I can install tweaks and widgets from it. 

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.1-74
 - iOS: iOS 14.1
 - Jailbreak: unc0ver
 - Device: iPhone 12 Pro Max

**Additional context**
When the source is added to Cydia on the same device, it loads with no problem and I can install tweaks from the repo.

**Comment by vanwijkdave** [comment]
This source is invalid, it also doesn't work on zebra and sileo. Furthermore I also can't acces the Packages file manually: https://ocean.webjungle.ch/Packages. My guess is that it once worked, and now its cached in your Cydia, making it appear working.

If you re-add the repo on Cydia it should also error, just like Installer. 

Hope this answer is sufficient!

**Comment by vanwijkdave** [comment]
I spoke too soon, tested it in Sileo again and it worked. This is a weird case, and we will investigate this further

**Comment by vanwijkdave** [comment]
It seems that the repo stores the packages in Bz2 format, instead of (normal) plaintext, we'll investigate the matter further

**Comment by SynnyGR** [comment]
Hi there,

I'm glad to announce that this bug have been fixed :)
In fact some repo return an http 510 error code when Installed try to download the Release file (this error code means that the server doesn't accept to respond correctly to a request without an extension and since the Release file doesn't have extension...). The solution was to try again with another type of request, and successfully refreshed the mentioned source!

This fix will be available within the next update.

Have a nice day.

Best regards
