### ISSUE TITLE
[BUG] Web depictions are not showing a lot of the time, and when I press open in safari, the app crashes.

### ISSUE THREAD

**Issue by Aahil52** [AppTapp/Installer-Issues#168]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Does the issue always occur when trying to reproduce it?** 
Yes

**Expected behavior**
Web depiction should show properly

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device (please complete the following information):**
 - Installer version: 5.1 beta
 - iOS: 14.2
 - Jailbreak unc0ver
 - Device iPhone 11 pro
![FB353807-4EA8-49D9-85F2-DC64C37F0551](https://user-images.githubusercontent.com/32886850/113193634-2e6d5480-922e-11eb-8a70-ec647487e2da.png)

**Additional context**

**Comment by rastafaa** [comment]
This happens to me too

**Comment by vanwijkdave** [comment]
This occurs when no web ánd no native depiction is found, there is nothing to show, and when you open the url in safari it'll crash because there is nothing to open. This happens when either the developer hasn't added a depiction, or when the repo is removed (or when the package is removed from the repo, like yt reborn in the above screenshot)

I've added an extra check, and when it can't find the url, it will now show the info it can get from the deb. See image below.

<img width="545" alt="Screenshot 2021-04-02 at 22 35 44" src="https://user-images.githubusercontent.com/31007683/113452160-c5d7d080-9403-11eb-8648-9ffbb92d5aeb.png">

**Comment by Aahil52** [comment]
Ok thank you, I've been turning off web depiction as fallback so I could see the description for tweaks that don't have depictions

**Comment by Aahil52** [comment]
Also how do I update installer to get these fixes?
