### ISSUE TITLE
[BUG] Search results are inaccurate

### ISSUE THREAD

**Issue by M1staAwesome** [AppTapp/Installer-Issues#3]
**Describe the bug**
If you search the exact name of a tweak, other tweaks that are similarly named or share some keywords with the search will show before the tweak that you searched for does

**To Reproduce**
Steps to reproduce the behaviour:
**1.** Search for any tweak by its exact name (I’ll use Snowboard as an example)
**2.** Notice how it isn’t the first result, even though it’s typed in exactly

**Does the issue always occur when trying to reproduce it?** 
Yes, although it doesn’t happen with all tweaks, just tweaks that are similarly named

**Expected behavior**
I expected Snowboard to be the first result, but it doesn’t even show in the first couple tweaks

**Screenshots or videos**
![334E8498-E6E7-43CB-BA46-7C3C8FDF8471](https://user-images.githubusercontent.com/37033149/70802786-09727b00-1d78-11ea-813d-d30f1062e89d.png)

**Device (please complete the following information):**
 - Installer version: 5.0RC5-1
 - iOS: 13.3
 - Jailbreak: checkra1n 0.9.6
 - Device iPhone 8 Plus

**Comment by CreatureSurvive** [comment]
I’ll address this issue later today. I will add a search filter so you can select between searching _exact phrase_ as you describe, and _fuzzy match_ which is how it currently is (matches a phrase anywhere in the title).

This should not take long to add, but it still might not make it into this coming version because I already pushed a significant amount of changes, and this might be released before I finish this.


Thanks for the suggestion, we appreciate it!
